### ISSUE TITLE
the question and answer are mismatch

### ISSUE THREAD

**Issue by Ericmututu** [night-chen/ToolQA#1]
Hi,

Thank you for sharing this wonderful dataset. I note a mismatch issue between question and answer in [Line 21-40](https://github.com/night-chen/ToolQA/blob/13090be4bc8faf3c00a5160ced862b73300ef79c/data/questions/hard/genda-hard.jsonl#L21). It seems to be caused by `dataset_generation/hard_questions/hard_agenda.ipynb` of `In [10]:`.

BTW, I am very curious about the detailed process of calling APIs during inference. Looking forward to Benchmark Code being released soon (:

**Comment by night-chen** [comment]
Thank you for pointing this out. This typo is made during our code cleaning, all the **"Who is unavailable..."** questions you have pointed out are all **"How many people are unavailable...?"**. We have made changes accordingly.

The benchmark code will be released before July 15th (the latest date). That commitment will include the tools implementations. Thank you for your interest in our work and your valuable suggestions!
