### ISSUE TITLE
The release of tool code

### ISSUE THREAD

**Issue by hsaest** [night-chen/ToolQA#2]
We greatly appreciate your work and intend to use it as a foundation for our research. I noticed that you've released the external corpus, but haven't provided instructions on how to use the tools mentioned in your paper. I was wondering if you have any plans to release the code that helps control these external tools?

Thank you ! Nice work!

**Comment by night-chen** [comment]
Thank you for your interest in our work. We plan to release the benchmark and tool code before July 15th. You can check it at that time. Thank you for your questions!

**Comment by hsaest** [comment]
This is excellent. I will continue to follow your outstanding work! Thank you so much! :)
